# Tetrahedron Volume with Quadrays

Testing a new enhancement shared with me by Tom Ace.

In [1]:
import numpy as np
from qrays import Qvector
from random import choice
from itertools import permutations
import tetravolume as tv

The four quadrays...

In [2]:
a = Qvector((1,0,0,0))
b = Qvector((0,1,0,0))
c = Qvector((0,0,1,0))
d = Qvector((0,0,0,1))

In [3]:
a.coords

ivm_vector(a=1, b=0, c=0, d=0)

In [4]:
def volume(q0, q1, q2, q3):
    """
    Construct a 5x5 matrix per Tom Ace
    """
    A = np.ones((5,5)) # shape, all 1s except..
    A[4,4] = 0 # zero in lower right corner
    A[0,0:4] = q0.coords
    A[1,0:4] = q1.coords
    A[2,0:4] = q2.coords
    A[3,0:4] = q3.coords
    return abs(np.linalg.det(A))/4 # that's it!

Getting back the expected unit-volume...

In [5]:
volume(a,b,c,d)

1.0

Double all Qvector lengths...

In [6]:
a, b, c, d = map(lambda q: 2 * q, (a,b,c,d))

Volume is 8-folded...

In [7]:
volume(a,b,c,d)

8.0

Create the 12 directions to neighoring balls in a ball packing.

In [8]:
moves = [Qvector(p) for p in set(permutations((2,1,1,0)))]
moves

[ivm_vector(a=0, b=1, c=1, d=2),
 ivm_vector(a=1, b=0, c=1, d=2),
 ivm_vector(a=2, b=0, c=1, d=1),
 ivm_vector(a=0, b=2, c=1, d=1),
 ivm_vector(a=0, b=1, c=2, d=1),
 ivm_vector(a=1, b=2, c=1, d=0),
 ivm_vector(a=1, b=1, c=2, d=0),
 ivm_vector(a=2, b=1, c=1, d=0),
 ivm_vector(a=1, b=0, c=2, d=1),
 ivm_vector(a=1, b=2, c=0, d=1),
 ivm_vector(a=2, b=1, c=0, d=1),
 ivm_vector(a=1, b=1, c=0, d=2)]

In [9]:
def random_walk(start, steps):
    """
    Randomly move in the 12 CCP directions
    for steps times, starting at start
    """
    end = start
    for _ in range(steps):
        end += choice(moves)
    return end 

vA = random_walk(Qvector((0,0,0,0)), 1000)
vB = random_walk(Qvector((0,0,0,0)), 1000)
vC = random_walk(Qvector((0,0,0,0)), 1000)
vD = random_walk(Qvector((0,0,0,0)), 1000)  

In [10]:
ab = (vA-vB).length()
ac = (vA-vC).length()
ad = (vA-vD).length()
bc = (vB-vC).length()
cd = (vC-vD).length()
bd = (vB-vD).length()

In [11]:
t = tv.Tetrahedron(ab,ac,ad,bc,cd,bd)
t.ivm_volume()

378.00000000126147

In [12]:
volume(vA, vB, vC, vD)

378.0000000000005

In [13]:
import gmpy2
from gmpy2 import mpfr
gmpy2.get_context().precision=200
z0 = mpfr('0')
vA = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vB = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vC = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vD = random_walk(Qvector((z0,z0,z0,z0)), 1000) 
ab = (vA-vB).length()
ac = (vA-vC).length()
ad = (vA-vD).length()
bc = (vB-vC).length()
cd = (vC-vD).length()
bd = (vB-vD).length()
t = tv.Tetrahedron(ab,ac,ad,bc,cd,bd)
t.ivm_volume()

mpfr('11068.0',200)

Since the inputs to the determinant will be only integers in this situation, force an integer result.  Should match the above.

In [14]:
def volume(q0, q1, q2, q3):
    A = np.ones((5,5), dtype=np.int64)
    A[4,4] = 0
    A[0,0:4] = q0.coords
    A[1,0:4] = q1.coords
    A[2,0:4] = q2.coords
    A[3,0:4] = q3.coords
    print(A)
    return int(round(abs(np.linalg.det(A))/4))

In [15]:
volume(vA, vB, vC, vD)

[[ 3 23 14  0  1]
 [ 0 29 40 19  1]
 [40 31 29  0  1]
 [39  0 23 38  1]
 [ 1  1  1  1  0]]


11068