[Oregon Curriculum Network](http://4dsolutions.net/ocn/)<br />
[Home Page](School_of_Tomorrow.ipynb)

# Tetrahedron Volume with Quadrays

Testing a new enhancement shared with me by Tom Ace.

$$
A = 
\begin{vmatrix}
a0&a1&a2&a3&1\\
b0&b1&b2&b3&1\\
c0&c1&c2&c3&1\\
d0&d1&d2&d3&1\\
1&1&1&1&0\\
\end{vmatrix}
$$
<br />

$$ 
Vol = |{A/4}|
$$

That's a determinant, which results in a number A, which upon dividing by 4, and taking the absolute value, gives the volume of said tetrahedron, in tetravolumes.

What tetrahedron again?  The one defined by the four Quadrays or Qvectors, vectors defined using 4-tuples additively combining 4 elementary rays from (0,0,0,0) to the 4 corners of a tetrahedron: (1,0,0,0) (0,1,0,0) (0,0,1,0) and (0,0,0,1).

In this implementation of Qvectors, the resulting home base tetrahedron is what has edges 1, not the elementary Qvectors.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/4723083407/in/photolist-2myMppk-2m29ok8-2jxGLDx-KjMqQP-EhaxK2-Bpf1cD-8P2cs1-8cn39x-7cVeMN-JotMo/" title="Quadray Coordinates"><img src="https://live.staticflickr.com/1213/4723083407_2ccf6bc229_w.jpg" width="400" height="350" alt="Quadray Coordinates"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

What about "tetravolumes"?  That's where we take a tetrahedron of edges 1, as unit volume, or edges 2 if measuring in radians (radii).  The Quadrays in question have been geared to operate in such a namespace, i.e. the balls below have radius R, diameter D, D = 2R.  That's our home base tetrahedron with (0,0,0,0) at its center of gravity.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/4949801610/in/photolist-2m29ojG-5DsYaY-2i3qGpP-8EDNfx-8xp2z5-6wUiRq" title="Sphere Packing"><img src="https://live.staticflickr.com/4146/4949801610_da3fc94b2c_n.jpg" width="240" height="320" alt="Sphere Packing"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

In [1]:
import numpy as np
from qrays import Qvector
from random import choice
from itertools import permutations
import tetravolume as tv

The four quadrays...

In [2]:
a = Qvector((1,0,0,0))
b = Qvector((0,1,0,0))
c = Qvector((0,0,1,0))
d = Qvector((0,0,0,1))

In [3]:
a.coords

ivm_vector(a=1, b=0, c=0, d=0)

In [4]:
def volume(q0, q1, q2, q3):
    """
    Construct a 5x5 matrix per Tom Ace
    """
    A = np.ones((5,5)) # shape, all 1s except..
    A[4,4] = 0 # zero in lower right corner
    A[0,0:4] = q0.coords
    A[1,0:4] = q1.coords
    A[2,0:4] = q2.coords
    A[3,0:4] = q3.coords
    return abs(np.linalg.det(A))/4 # that's it!

Getting back the expected unit-volume...

In [5]:
volume(a,b,c,d)

1.0

Double all Qvector lengths...

In [6]:
a, b, c, d = map(lambda q: 2 * q, (a,b,c,d))

Volume is 8-folded...

Create the 12 directions to neighoring balls in a ball packing.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/51522139740/in/photolist-8thDyL-2muQr99-2msgzQd-2msj6xS-2mgJNog-2m44aqr-22yg9uX-FMLvQQ-NzckH4-EPg3Ag-CMbRqK-dMGmVw-agu9Xx-8xp2z5-8vatB3-8ti2xi-8oX85J-6Wcvue-5QyKim" title="Growing Sphere Packing"><img src="https://live.staticflickr.com/65535/51522139740_b16f97cc96_m.jpg" width="225" height="210" alt="Growing Sphere Packing"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

In [7]:
moves = [Qvector(p) for p in set(permutations((2,1,1,0)))]
moves

[ivm_vector(a=0, b=1, c=1, d=2),
 ivm_vector(a=1, b=0, c=1, d=2),
 ivm_vector(a=2, b=0, c=1, d=1),
 ivm_vector(a=0, b=2, c=1, d=1),
 ivm_vector(a=0, b=1, c=2, d=1),
 ivm_vector(a=1, b=2, c=1, d=0),
 ivm_vector(a=1, b=1, c=2, d=0),
 ivm_vector(a=2, b=1, c=1, d=0),
 ivm_vector(a=1, b=0, c=2, d=1),
 ivm_vector(a=1, b=2, c=0, d=1),
 ivm_vector(a=2, b=1, c=0, d=1),
 ivm_vector(a=1, b=1, c=0, d=2)]

In [8]:
def random_walk(start, steps):
    """
    Randomly move in the 12 CCP directions
    for steps times, starting at start
    """
    end = start
    for _ in range(steps):
        end += choice(moves)
    return end 

vA = random_walk(Qvector((0,0,0,0)), 1000)
vB = random_walk(Qvector((0,0,0,0)), 1000)
vC = random_walk(Qvector((0,0,0,0)), 1000)
vD = random_walk(Qvector((0,0,0,0)), 1000)  

In [9]:
ab = (vA-vB).length()
ac = (vA-vC).length()
ad = (vA-vD).length()
bc = (vB-vC).length()
cd = (vC-vD).length()
bd = (vB-vD).length()

The volume formula used in tv.Tetrahedron operates on the six edge lengths only.  

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/39391693474/in/photolist-2msgpP9-2ifuQn8-2hvwJt9-2csiBa8-231UJ5S-QrfReH-GNshah-q8vyLo-fwsLq7-fwdt8t-fwsE89-fwsARu-c5RPLS-bH5gvP-8xp1nN-8tm3iL-8teDJ4-8thDyL-8thDHW-8ryECF-8ryEix-8teEm2-8ryyt2-8pNQou-8thE4q-5QyKsS-7jZLhp-8batec-7cXk2G-6n24Ja-5QyKe7" title="Computer Volume"><img src="https://live.staticflickr.com/4672/39391693474_c6c54f3d22.jpg" width="500" height="463" alt="Computer Volume"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>


The formula originally comes from Gerald de Jong, a tensegrity master and an inventor of "elastic interval geometry".

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/49649798053/in/photolist-2iDocbV" title="Pretty Shadows by Gerald de Jong"><img src="https://live.staticflickr.com/65535/49649798053_729ac6bf74_w.jpg" width="400" height="300" alt="Pretty Shadows by Gerald de Jong"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

In [10]:
t = tv.Tetrahedron(ab,ac,ad,bc,cd,bd)
t.ivm_volume()

11970.000000000318

In [11]:
volume(vA, vB, vC, vD)

11970.000000000002

These vestigal rounding errors are annoying.  Lets employ some arbitrary precision numbers, allowing 200 bits per number object.  If you grab a copy of this Notebook and install gmpy2, you will be able to adjust the precision.

In [12]:
import gmpy2
from gmpy2 import mpfr
gmpy2.get_context().precision=200
z0 = mpfr('0')
vA = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vB = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vC = random_walk(Qvector((z0,z0,z0,z0)), 1000)
vD = random_walk(Qvector((z0,z0,z0,z0)), 1000) 
ab = (vA-vB).length()
ac = (vA-vC).length()
ad = (vA-vD).length()
bc = (vB-vC).length()
cd = (vC-vD).length()
bd = (vB-vD).length()
t = tv.Tetrahedron(ab,ac,ad,bc,cd,bd)
t.ivm_volume()

mpfr('73173.999999999999999999999999999999999999999999999999999999674',200)

Since the inputs to the determinant will be only integers in this situation, force an integer result.  Should match the above.  numpy speeds determinant finding, using short cuts that introduce some entropy.

Since we know from other homework that tetrahedrons randomly generated by the method described have integer volume, we're fine with rounding and typecasting to int as a last step, in the version of the volume function below.

In [13]:
def volume(q0, q1, q2, q3):
    A = np.ones((5,5), dtype=np.int64)
    A[4,4] = 0
    A[0,0:4] = q0.coords
    A[1,0:4] = q1.coords
    A[2,0:4] = q2.coords
    A[3,0:4] = q3.coords
    print(A)
    return int(round(abs(np.linalg.det(A))/4))

In [14]:
volume(vA, vB, vC, vD)

[[ 6  0 17 37  1]
 [ 0 54 61 25  1]
 [45 40  0 23  1]
 [69  0 27 20  1]
 [ 1  1  1  1  0]]


73174

For further reading:

* [Random Walk in the Matrix](https://nbviewer.org/github/4dsolutions/elite_school/blob/master/Quadrays.ipynb)
* [The Quadray Papers](http://grunch.net/synergetics/quadrays.html)
* [Quadray Coordinates on Wikipedia](https://en.wikipedia.org/wiki/Quadray_coordinates)
* [Cartesian Coordinates and simplicial coordinates](https://minortriad.com/q4d.html)